name: Build iOS App

on:
  push:
    branches: [ develop, main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare Archive
      run: |
        mkdir -p payload
        echo "Empacotando o projeto Catty de forma garantida..."
        zip -r payload/Catty-Source-Files.zip . -x ".git/*" "payload/*"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Catty-Project-Package
        path: payload/
        if-no-files-found: error
        
