    - name: Build Project
      run: |
        echo "Buscando o projeto..."
        xcodebuild -list
        
        echo "Compilando o aplicativo..."
        xcodebuild -workspace *.xcworkspace -scheme Catty -sdk iphoneos -configuration Release archive -archivePath $PWD/build/Catty.xcarchive
        
        echo "Exportando o IPA..."
        xcodebuild -exportArchive -archivePath $PWD/build/Catty.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build/
        
